// vue3-js-app/src/components/requirement-center/ProductionWorkspace.vue
<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import ProductionCalendarView from './ProductionCalendarView.vue'
import ProductionCapacityView from './ProductionCapacityView.vue'
import ProductionGanttView from './ProductionGanttView.vue'
import ProductionRiskModal from './ProductionRiskModal.vue'
import ProductionScheduleHeader from './ProductionScheduleHeader.vue'
import { useProductionPlanning } from './useProductionPlanning'

const props = defineProps({
  requirements: {
    type: Array,
    default: () => [],
  },
  schedules: {
    type: Array,
    default: () => [],
  },
  todayDateString: {
    type: String,
    required: true,
  },
})

const emit = defineEmits(['open-requirement'])

const workspaceRootRef = ref(null)
const requirementsRef = computed(() => props.requirements)
const schedulesRef = computed(() => props.schedules)

const {
  productionView,
  selectedProducers,
  isProducerFilterOpen,
  showProductionRiskModal,
  calendarYear,
  calendarMonth,
  productionTasks,
  delayedProductionRiskItems,
  activeProducers,
  personnelCapacityGroups,
  productionGanttStart,
  productionGanttDays,
  productionGanttRows,
  productionCalendarWeeks,
  handlePrevMonth,
  handleNextMonth,
  jumpToday,
  toggleProducer,
} = useProductionPlanning({
  requirements: requirementsRef,
  schedules: schedulesRef,
  todayDateString: props.todayDateString,
})

const closeOpenMenus = () => {
  isProducerFilterOpen.value = false
}

const handleDocumentClick = (event) => {
  if (!workspaceRootRef.value?.contains(event.target)) closeOpenMenus()
}

const handleDocumentKeydown = (event) => {
  if (event.key === 'Escape') closeOpenMenus()
}

onMounted(() => {
  document.addEventListener('click', handleDocumentClick)
  document.addEventListener('keydown', handleDocumentKeydown)
})

onBeforeUnmount(() => {
  document.removeEventListener('click', handleDocumentClick)
  document.removeEventListener('keydown', handleDocumentKeydown)
})
</script>

<template>
  <div ref="workspaceRootRef" class="relative flex flex-1 flex-col gap-4 overflow-hidden">
    <ProductionScheduleHeader
      :production-view="productionView"
      :delayed-count="delayedProductionRiskItems.length"
      :selected-producers="selectedProducers"
      @production-view-change="productionView = $event"
      @open-risk-modal="showProductionRiskModal = true"
      @clear-selected-producers="selectedProducers = []"
    />

    <Teleport to="body">
      <ProductionRiskModal v-if="showProductionRiskModal" :items="delayedProductionRiskItems" @close="showProductionRiskModal = false" />
    </Teleport>

    <div class="flex-1 overflow-auto rounded-2xl border border-slate-150 bg-white p-4 shadow-3xs">
      <ProductionCapacityView
        v-if="productionView === 'capacity'"
        :groups="personnelCapacityGroups"
        @select-producer="
          selectedProducers = [$event];
          productionView = 'calendar'
        "
      />

      <ProductionCalendarView
        v-else-if="productionView === 'calendar'"
        :calendar-year="calendarYear"
        :calendar-month="calendarMonth"
        :calendar-weeks="productionCalendarWeeks"
        :production-tasks="productionTasks"
        :selected-producers="selectedProducers"
        :active-producers="activeProducers"
        :is-producer-filter-open="isProducerFilterOpen"
        @jump-today="jumpToday"
        @prev-month="handlePrevMonth"
        @next-month="handleNextMonth"
        @toggle-producer-filter="isProducerFilterOpen = !isProducerFilterOpen"
        @clear-producers="
          selectedProducers = [];
          isProducerFilterOpen = false
        "
        @toggle-producer="toggleProducer"
        @open-requirement="emit('open-requirement', $event)"
      />

      <ProductionGanttView
        v-else
        :gantt-start="productionGanttStart"
        :days="productionGanttDays"
        :rows="productionGanttRows"
        :selected-producers="selectedProducers"
        @select-producer="selectedProducers = [$event]"
        @open-requirement="emit('open-requirement', $event)"
      />
    </div>
  </div>
</template>

// components/requirement-center/ProductionWorkspace.tsx
import type React from "react";
import type { Requirement } from "../../types";
import type { Producer } from "./people";
import type { CalendarWeek } from "./dateUtils";
import type { ScheduledTaskView } from "./requirementUtils";
import { ProductionCalendarView } from "./ProductionCalendarView";
import { ProductionCapacityView } from "./ProductionCapacityView";
import { ProductionGanttView } from "./ProductionGanttView";
import { ProductionScheduleHeader } from "./ProductionScheduleHeader";

type ProductionView = "capacity" | "calendar" | "gantt";

type CapacityRow = {
  producer: Producer;
  weekTasks: ScheduledTaskView[];
  loadRate: number;
  nextAvailable: string;
};

type GanttDay = {
  dateString: string;
  day: number;
  month: number;
  isToday: boolean;
  isWeekend: boolean;
};

type GanttRow = {
  producer: Producer;
  tasks: ScheduledTaskView[];
};

export const ProductionWorkspace = ({
  productionView,
  delayedCount,
  selectedProducers,
  personnelCapacityGroups,
  calendarYear,
  calendarMonth,
  calendarWeeks,
  productionTasks,
  isProducerFilterOpen,
  producerFilterRef,
  activeProducers,
  ganttStart,
  ganttDays,
  ganttRows,
  onProductionViewChange,
  onOpenRiskModal,
  onSelectedProducersChange,
  onJumpToday,
  onPrevMonth,
  onNextMonth,
  onToggleProducerFilter,
  onClearProducerFilter,
  onToggleProducer,
  onOpenRequirement,
}: {
  productionView: ProductionView;
  delayedCount: number;
  selectedProducers: string[];
  personnelCapacityGroups: Record<string, CapacityRow[]>;
  calendarYear: number;
  calendarMonth: number;
  calendarWeeks: CalendarWeek[];
  productionTasks: ScheduledTaskView[];
  isProducerFilterOpen: boolean;
  producerFilterRef: React.RefObject<HTMLDivElement>;
  activeProducers: Producer[];
  ganttStart: string;
  ganttDays: GanttDay[];
  ganttRows: GanttRow[];
  onProductionViewChange: (view: ProductionView) => void;
  onOpenRiskModal: () => void;
  onSelectedProducersChange: (producers: string[]) => void;
  onJumpToday: () => void;
  onPrevMonth: () => void;
  onNextMonth: () => void;
  onToggleProducerFilter: () => void;
  onClearProducerFilter: () => void;
  onToggleProducer: (producerName: string) => void;
  onOpenRequirement: (requirement: Requirement) => void;
}) => (
  <div className="flex-1 flex flex-col gap-4 overflow-hidden relative">
    <ProductionScheduleHeader
      productionView={productionView}
      delayedCount={delayedCount}
      selectedProducers={selectedProducers}
      onProductionViewChange={onProductionViewChange}
      onOpenRiskModal={onOpenRiskModal}
      onClearSelectedProducers={() => onSelectedProducersChange([])}
    />

    <div className="flex-1 overflow-auto rounded-2xl border border-slate-150 bg-white p-4 shadow-3xs">
      {productionView === "capacity" ? (
        <ProductionCapacityView
          personnelCapacityGroups={personnelCapacityGroups}
          onSelectProducer={(producerName) => {
            onSelectedProducersChange([producerName]);
            onProductionViewChange("calendar");
          }}
        />
      ) : productionView === "calendar" ? (
        <ProductionCalendarView
          calendarYear={calendarYear}
          calendarMonth={calendarMonth}
          calendarWeeks={calendarWeeks}
          productionTasks={productionTasks}
          selectedProducers={selectedProducers}
          isProducerFilterOpen={isProducerFilterOpen}
          producerFilterRef={producerFilterRef}
          activeProducers={activeProducers}
          onJumpToday={onJumpToday}
          onPrevMonth={onPrevMonth}
          onNextMonth={onNextMonth}
          onToggleProducerFilter={onToggleProducerFilter}
          onClearProducers={onClearProducerFilter}
          onToggleProducer={onToggleProducer}
          onOpenRequirement={onOpenRequirement}
        />
      ) : (
        <ProductionGanttView
          ganttStart={ganttStart}
          days={ganttDays}
          rows={ganttRows}
          selectedProducers={selectedProducers}
          onSelectProducer={(producerName) => onSelectedProducersChange([producerName])}
          onOpenRequirement={onOpenRequirement}
        />
      )}
    </div>
  </div>
);
